[package]
name = "rink"
version = "0.4.3"
authors = ["Tiffany Bennett <tiffany@stormbit.net>"]
description = "Unit conversion tool and library, similar to frink"
homepage = "https://github.com/tiffany352/rink-rs"
repository = "https://github.com/tiffany352/rink-rs"
readme = "README.md"
license = "MPL-2.0"
keywords = ["unit", "math", "conversion", "cli", "tool"]

[features]
default = ["linefeed", "chrono-humanize", "gpl", "currency"]
sandbox = ["libc", "ipc-channel"]
gpl = []
currency = ["hyper", "hyper-native-tls", "xml-rs", "json"]
nightly = ["serde", "serde_derive"]

[dependencies]
rust-gmp = "0.5.0"
chrono = "0.2.25"
strsim = "0.8.0"
chrono-tz = "0.2.2"
chrono-humanize = { version = "0.0.11", optional = true }
linefeed = { version = "0.4.0", optional = true }
hyper = { version = "0.10.10", optional = true }
hyper-native-tls = { version = "0.3", optional = true }
libc = { version = "0.2.43", optional = true }
ipc-channel = { version = "0.11.2", optional = true }
xml-rs = { version = "0.8.0", optional = true }
json = { version = "0.11.13", optional = true }
serde = { version = "0.8.16", optional = true }
serde_derive = { version = "0.8.16", optional = true }

[[bin]]
name = "rink"
doc = false

[workspace]
members = ["web", "irc"]
